# Generated by Django 4.2.24 on 2025-09-10 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ttl',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scantask'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='service',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
