# Generated by Django 4.2.24 on 2025-09-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_reason_scanresult_ttl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanner.scantask'),
        ),
    ]
