# Generated by Django 4.2.24 on 2025-09-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_scanresult_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scantask'),
        ),
    ]
