# Generated by Django 4.2.24 on 2025-11-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scanresult_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
